#:schema node_modules/wrangler/config-schema.json
name = "twitch-cloud-ebs"
main = "src/index.js"
compatibility_date = "2025-01-09"

[route]
pattern="ebs.sugoidogo.com"
custom_domain=true

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[observability]
enabled = true

# Workers Assets
# Docs: https://developers.cloudflare.com/workers/static-assets/binding/
[assets]
directory = "./static/"
binding = "static"
experimental_serve_directly = false 

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Docs:
# - https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# Use secrets to store sensitive data.
# - https://developers.cloudflare.com/workers/configuration/secrets/
[vars]
serve_static = true

# Automatically place your workloads in an optimal location to minimize latency.
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# [placement]
# mode = "smart"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets
[[r2_buckets]]
binding = "storage"
bucket_name = "sugoi-web-services"
preview_bucket_name = "sugoi-web-services-testing"
jurisdiction = "eu"