# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "twitch-cloud-ebs"
main = "src/index.ts"
compatibility_date = "2025-10-11"
compatibility_flags = [ "global_fetch_strictly_public" ]
keep_vars=true
workers_dev=false

[build]
command='esbuild *.ts --outdir=. --minify --bundle --sourcemap=inline --sources-content=false --format=esm'
cwd='public'

[assets]
directory = "./public"

[observability]
enabled = true

[placement]
mode = "smart"